name: flutter_application_smartshop
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  shared_preferences: ^2.2.3
  sqflite: any
  path: any
  intl: any
  another_flushbar: ^1.12.30
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  date_field: ^5.2.1
  loading_animation_widget: ^1.2.1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/products/
    - assets/images/categories/
    # - assets/files/
